version: '3'
services:
    service:
        container_name : 'service-api'
        build:
            context: 
                ./service/
            dockerfile: Dockerfile
        image : 'abderoxdocker/bookery-backend'
        ports:
            - "8085:8085"
        networks:
            -  bookery-app
        volumes:
          - ./service:/usr/src/app/service
          - /usr/src/app/service/node_modules
        

    ui:
        container_name : 'ui-client'
        build: 
            context: ./ui/
            dockerfile: Dockerfile
        image: 'abderoxdocker/bookery-front-prod:local'
        ports:
            - "8888:80"
            - "443:80"
        depends_on:
            - service
        networks:
            - bookery-app
        volumes:
            - ./ui:/usr/src/app
            - /usr/src/app/node_modules

networks:
    bookery-app:
      driver: bridge

